### ISSUE TITLE
missing file 'modules'

### ISSUE THREAD

**Issue by cocoa1231** [avielw/kplugs#1]
Release directory already exists
cp Makefile.release Release/Makefile
cp Makefile.debug   Debug/Makefile
cp *.c *.S *.h Release
cp *.c *.S *.h Debug
make[1]: Entering directory '/home/jatin/Downloads/Extracted-Files/kplugs-master/Release'
make[2]: Entering directory '/usr/lib/modules/4.8.10-1-ARCH/build'
make[2]: *** No rule to make target 'modules'.  Stop.
make[2]: Leaving directory '/usr/lib/modules/4.8.10-1-ARCH/build'
make[1]: *** [Makefile:9: all] Error 2
make[1]: Leaving directory '/home/jatin/Downloads/Extracted-Files/kplugs-master/Release'
make: *** [Makefile:17: all] Error 2

**Comment by avielw** [comment]
Do you have your kernel headers in "/usr/lib/modules/4.8.10-1-ARCH/build"?

**Comment by cocoa1231** [comment]
Yes I do

**Comment by avielw** [comment]
Did you change anything? It's using a different path on your log. (It should be /lib/modules/`uname -r`/build)
It seems like you have a problem with your headers. The **build** file should point to the headers.
Can you send the contents of the build directory?
